
package carreracaballos403;

import javax.swing.JLabel;

public class Caballos403 extends javax.swing.JFrame {

   
    public Caballos403() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Copa Piston");
    }
    public JLabel getCaballoUno(){
    return CaballoUno;
    }
    public JLabel getCaballoDos(){
    return CaballoDos;
    }
    public JLabel getCaballoTres(){
    return CaballoTres;
    }
    public JLabel getCaballoCuatro(){
    return CaballoCuatro;
    }
    public JLabel getCaballoCinco(){
    return CaballoCinco;
    }
    public JLabel getMeta(){
    return Meta;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * generated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CaballoUno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IniciarCarrerra = new javax.swing.JButton();
        Meta = new javax.swing.JLabel();
        CaballoDos = new javax.swing.JLabel();
        CaballoTres = new javax.swing.JLabel();
        CaballoCuatro = new javax.swing.JLabel();
        CaballoCinco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CaballoUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/c5.jpeg"))); // NOI18N
        CaballoUno.setText("Riana ");

        jLabel4.setText("Copa piston");

        IniciarCarrerra.setText("Inicio");
        IniciarCarrerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarCarrerraActionPerformed(evt);
            }
        });

        Meta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/meta.jpeg"))); // NOI18N
        Meta.setText("meta");

        CaballoDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/c4.jpeg"))); // NOI18N
        CaballoDos.setText("Rayo");

        CaballoTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/c3.jpeg"))); // NOI18N
        CaballoTres.setText("brayan");

        CaballoCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/c2.jpeg"))); // NOI18N
        CaballoCuatro.setText("roger");

        CaballoCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos403/c1.jpeg"))); // NOI18N
        CaballoCinco.setText("Rashell");
        CaballoCinco.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CaballoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(599, 599, 599)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(770, 791, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CaballoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaballoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CaballoCinco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CaballoCuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IniciarCarrerra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(736, 736, 736))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(CaballoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaballoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaballoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaballoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CaballoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IniciarCarrerra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarCarrerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarCarrerraActionPerformed
        // TODO add your handling code here:
        CaballoUno.setLocation(0,CaballoUno.getLocation().y);
        CaballoDos.setLocation(0,CaballoDos.getLocation().y);
        CaballoTres.setLocation(0,CaballoTres.getLocation().y);
        CaballoCuatro.setLocation(0,CaballoCuatro.getLocation().y);
        CaballoCinco.setLocation(0,CaballoCinco.getLocation().y);
        
       Runnable caballo1 = new Caballo(CaballoUno, this);
        Runnable caballo2 = new Caballo(CaballoDos, this);
        Runnable caballo3 = new Caballo(CaballoTres, this);
        Runnable caballo4 = new Caballo(CaballoCuatro, this);
        Runnable caballo5 = new Caballo(CaballoCinco, this);
        
        
       Thread hilo1 = new Thread(caballo1);
        Thread hilo2 = new Thread(caballo2);
        Thread hilo3 = new Thread(caballo3);
        Thread hilo4 = new Thread(caballo4);
        Thread hilo5 = new Thread(caballo5);

        // Iniciar los hilos
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        hilo5.start();
    }//GEN-LAST:event_IniciarCarrerraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caballos403.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caballos403.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caballos403.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caballos403.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caballos403().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaballoCinco;
    private javax.swing.JLabel CaballoCuatro;
    private javax.swing.JLabel CaballoDos;
    private javax.swing.JLabel CaballoTres;
    private javax.swing.JLabel CaballoUno;
    private javax.swing.JButton IniciarCarrerra;
    private javax.swing.JLabel Meta;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}



